# Generated by Django 4.1.3 on 2022-12-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteostations',
            name='id_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
