# Generated by Django 4.1.3 on 2022-12-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_meteostations_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteostations',
            name='coordinate_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteostations',
            name='coordinate_lon',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteostations',
            name='current_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteostations',
            name='rain_last_24',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteostations',
            name='uid',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
