# Generated by Django 4.1.3 on 2022-12-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_meteostations_coordinate_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsToStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_service_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('comment_text', models.TextField()),
            ],
        ),
    ]
