# Generated by Django 4.1.3 on 2022-12-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_commentstostation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentstostation',
            old_name='station_service_name',
            new_name='station_uid',
        ),
    ]
